### ISSUE TITLE
installation with lammps failing

### ISSUE THREAD

**Issue by nisargjoshi10** [mir-group/pair_nequip#10]
Hi all, 

I have been trying to install nequip with lammps but running into an error. I am running macOS system with Mojave 10.14.4

I am able to run the cmake command but when I run the last step `make -j6`, I get the following error:

```
[100%] Linking CXX static library liblammps.a
[100%] Built target lammps
[100%] Building CXX object CMakeFiles/lmp.dir/Users/nisarg/Desktop/nequip/nequip/lammps/src/main.cpp.o
[100%] Linking CXX executable lmp
Undefined symbols for architecture x86_64:
  "long* at::TensorBase::data_ptr<long>() const", referenced from:
      at::TensorAccessor<long, 1ul, at::DefaultPtrTraits, long long> at::TensorBase::accessor<long, 1ul>() const & in liblammps.a(pair_nequip.cpp.o)
      at::TensorAccessor<long, 2ul, at::DefaultPtrTraits, long long> at::TensorBase::accessor<long, 2ul>() const & in liblammps.a(pair_nequip.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lmp] Error 1
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
make: *** [all] Error 2

```

Thanks for the help!

Nisarg

**Comment by nisargjoshi10** [comment]
Thanks for the quick reply, I'll reach out there and see if I can work it on macOS. I've been trying to install it on Linux system as well but for some reason my PyTorch doesnt seem to work

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'utils'
cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by cmake)

```

I believe I can still train and deploy a model with NequIP without LAMMPS, just wondering if you suggest any other alternative methods to run the ML potential?

**Comment by Linux-cpp-lisp** [comment]
Hm, that's a strange pair of errors on the Linux... never seen that. Sometimes if you have too much of libc etc in your conda they can conflict with the system global ones and produce weird errors.

But the `no attribute 'utils'` is bizzare... would check for that in torch documentation too.

Yes, you can train, evaluate, etc. NequIP models without LAMMPS. If you want to evaluate your potential on some specific configurations, `nequip-evaluate` can do that for you. For small-scale MD, ASE (the Python Atomic Simulation Environment) is also an option; NequIP provides an ASE calculator in `nequip.ase.NequIPCalculator`.

**Comment by nisargjoshi10** [comment]
Great! I'll try to work with ASE till I figure out my issues. 

I have also tried making separate environments on conda and tried reinstalling pytorch. Do you know if NequIP is now compatible with pytorch 1.11? I saw an earlier issue that there were some issues with pytorch 1.11 and since then I've been working with v1.10, but I could try with the latest version and see if I can reproduce the same issues.

**Comment by Linux-cpp-lisp** [comment]
On the Python side it is likely compatible, but I have not tested this on the released version yet. (I ran unit tests at some point in the past on one of the release candidates, but that doesn't say too much.)

On the LAMMPS side, 1.11 is not yet supported. I hope to fix this in the coming days.

Please file issues if you encounter any issues from PyTorch 1.11 incompatibility! Thanks :smile:

**Comment by Linux-cpp-lisp** [comment]
@nisargjoshi10:

The latest NequIP and `pair_nequip` `develop` branches should now be PyTorch 1.11 compatible; please let me know if this resolves your installation issues and/or you encounter any other issues related to PyTorch 1.11.

**Comment by nisargjoshi10** [comment]
@Linux-cpp-lisp thanks for the update! I'll try to compile it today and let you know if there are any issues.

**Comment by nisargjoshi10** [comment]
@Linux-cpp-lisp I tried compiling it with PyTorch 1.11 on macOS but again getting the same issue. I'll have to wait until I get it working for Linux.

I also had a followup question for using NequIP with ASE. I'm trying to run an MD simulation with the trained model using the following code, but cant make it to work. Not sure if I'm using it wrong but if you have any feedback that'd be great:

```
calc_neq = NequIPCalculator(model='water-aimd-vasp.pth', r_max=4.5, device='cpu')
water = read('/Users/nisarg/Desktop/deepmd-kit/packmol/examples/water_52.pdb')
water.set_calculator(calc_neq)
md = NVTBerendsen(water, 0.5 * units.fs, 300, 0.005)
md.run(4000)

```
and the error is` TypeError: 'str' object is not callable` 

```
File ~/opt/anaconda3/envs/nequip/lib/python3.8/site-packages/ase/md/md.py:137, in MolecularDynamics.run(self, steps)
    135 """ Call Dynamics.run and adjust max_steps """
    136 self.max_steps = steps + self.nsteps
--> 137 return Dynamics.run(self)
```

I'm new to ASE and I might have messed up the steps for using the calculator as I'm getting the same error for `water.get_potential_energy()`

Thanks for the help!

**Comment by Linux-cpp-lisp** [comment]
Hi @nisargjoshi10 

As I said, we do not support macOS. On Linux it should now work.

For your ASE followup, can you please open a new discussion in mir-group/nequip and include the full error traceback?

**Comment by nisargjoshi10** [comment]
@Linux-cpp-lisp 

I'm trying to compile on Linux system, have you seen this error

```
[ 98%] Building CXX object CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/write_coeff.cpp.o
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp: In member function ‘virtual void LAMMPS_NS::PairNEQUIP::init_style()’:
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp:97:33: error: ‘int LAMMPS_NS::NeighRequest::half’ is protected within this context
   neighbor->requests[irequest]->half = 0;
                                 ^~~~
In file included from /mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp:26:0:
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/neigh_request.h:54:7: note: declared protected here
   int half;    // half neigh list (set by default)
       ^~~~
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp:98:33: error: ‘int LAMMPS_NS::NeighRequest::full’ is protected within this context
   neighbor->requests[irequest]->full = 1;
                                 ^~~~
In file included from /mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp:26:0:
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/neigh_request.h:55:7: note: declared protected here
   int full;    // full neigh list
       ^~~~
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp:101:33: error: ‘int LAMMPS_NS::NeighRequest::ghost’ is protected within this context
   neighbor->requests[irequest]->ghost = 0;
                                 ^~~~~
In file included from /mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp:26:0:
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/neigh_request.h:68:7: note: declared protected here
   int ghost;           // 1 if includes ghost atom neighbors
       ^~~~~
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/variable.cpp: In member function ‘int LAMMPS_NS::Variable::next(int, char**)’:
/mnt/c/Users/stlp/Desktop/nequip/lammps/src/variable.cpp:709:14: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         fread(buf,1,64,fp);
         ~~~~~^~~~~~~~~~~~~
[ 98%] Building CXX object CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/write_data.cpp.o
[ 98%] Building CXX object CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/write_dump.cpp.o
[ 98%] Building CXX object CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/write_restart.cpp.o
[100%] Building CXX object CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/STUBS/mpi.cpp.o
CMakeFiles/lammps.dir/build.make:8102: recipe for target 'CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp.o' failed
make[2]: *** [CMakeFiles/lammps.dir/mnt/c/Users/stlp/Desktop/nequip/lammps/src/pair_nequip.cpp.o] Error 1
CMakeFiles/Makefile2:805: recipe for target 'CMakeFiles/lammps.dir/all' failed
make[1]: *** [CMakeFiles/lammps.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Linux-cpp-lisp** [comment]
@anjohan is this the lammps version incompatability?

**Comment by anjohan** [comment]
Yes. For the time being, use the `stable_29Sep2021_update2` tag.
